// generateSite.js
// ---------------------------------------------------------------
// Uses Claude to generate a single-file starter website for a
// prospect. Output is dropped into agents/generated-sites/<slug>/.
//
// You can then open index.html locally to preview it, or send it
// to the business as a "free preview" attachment / link.
//
// Usage (single prospect by name):
//   node src/generateSite.js "Luxe Nails"
//
// Usage (batch — generates a site for every prospect in prospects.json):
//   node src/generateSite.js --all
// ---------------------------------------------------------------

import fs from "node:fs/promises";
import path from "node:path";
import Anthropic from "@anthropic-ai/sdk";
import { config, dataDir, sitesDir } from "./config.js";

const MODEL = "claude-opus-4-6";

function slugify(s) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
}

function buildPrompt(prospect) {
  return `Create a complete single-file starter website for this local business.

Business:
  Name: ${prospect.name}
  Category: ${prospect.category}
  Address: ${prospect.address}
  Phone: ${prospect.phone || "(not listed)"}

Requirements:
- ONE self-contained index.html (HTML + <style> + minimal <script> all inline).
- Mobile-first, responsive, accessible.
- Sections: sticky nav, hero with a clear value prop, about, services or menu,
  contact (phone + address + simple form), footer.
- Clean modern design that fits the business category (warm for a bakery,
  trustworthy blues for a plumber, elegant for a nail salon, etc.).
- Use CSS variables for colors so the palette is easy to tweak.
- Use system fonts — no external font or asset downloads.
- Do NOT invent fake reviews, awards, hours, or menu items. Use clear
  placeholder text like "Add your menu here" where specifics are unknown.
- No tracking scripts, no external JS libraries.
- At the very bottom of the footer, include:
    "Website preview by ${config.me.name} — ${config.me.portfolio}"

Return ONLY the raw HTML file contents. No markdown, no commentary, no code fences.`;
}

export async function generateSiteFor(prospect) {
  const client = new Anthropic({ apiKey: config.anthropicKey() });

  const msg = await client.messages.create({
    model: MODEL,
    max_tokens: 8000,
    messages: [{ role: "user", content: buildPrompt(prospect) }],
  });

  let html = msg.content
    .filter((b) => b.type === "text")
    .map((b) => b.text)
    .join("")
    .trim();

  // Strip accidental code fences
  html = html.replace(/^```(?:html)?\s*/i, "").replace(/\s*```$/i, "").trim();

  const slug = slugify(prospect.name);
  const outDir = path.join(sitesDir, slug);
  await fs.mkdir(outDir, { recursive: true });

  const outFile = path.join(outDir, "index.html");
  await fs.writeFile(outFile, html);

  // Drop a small README so Simone remembers what this is
  const readme = `# ${prospect.name} — preview site

Generated by the outreach agent on ${new Date().toISOString().slice(0, 10)}.

Business info used:
- Category: ${prospect.category}
- Address:  ${prospect.address}
- Phone:    ${prospect.phone || "(not listed)"}

Open \`index.html\` in a browser to preview.
`;
  await fs.writeFile(path.join(outDir, "README.md"), readme);

  return outFile;
}

async function loadProspects() {
  const p = path.join(dataDir, "prospects.json");
  return JSON.parse(await fs.readFile(p, "utf8"));
}

async function main() {
  const args = process.argv.slice(2);
  const prospects = await loadProspects();

  let target;
  if (args[0] === "--all") {
    target = prospects;
  } else if (args[0]) {
    const needle = args[0].toLowerCase();
    target = prospects.filter((p) => p.name.toLowerCase().includes(needle));
    if (!target.length) {
      console.error(`No prospect matches "${args[0]}".`);
      process.exit(1);
    }
  } else {
    console.error(
      'Usage:\n  node src/generateSite.js "Business Name"\n  node src/generateSite.js --all'
    );
    process.exit(1);
  }

  for (const p of target) {
    process.stdout.write(`Generating site for ${p.name}... `);
    try {
      const file = await generateSiteFor(p);
      console.log(`→ ${path.relative(process.cwd(), file)}`);
    } catch (err) {
      console.log(`FAILED (${err.message})`);
    }
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
